//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class KHACHHANG
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]

        public int MaKH { get; set; }
        [Required(ErrorMessage = "Tên khách hàng không được trống")]
        [StringLength(50, MinimumLength = 3)]

        public string TenKH { get; set; }
        [Required(ErrorMessage = "Địa chỉ không được trống")]
        [StringLength(50, MinimumLength = 3)]

        public string DiaChi { get; set; }
        [Required(ErrorMessage ="Email không được trống")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được trống")]
        [RegularExpression(@"^\(?([0-9]{3})\)([0-9]{3})([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string Sdt { get; set; }
        [Required(ErrorMessage ="Mật khẩu không được trống")]
        [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$", ErrorMessage = "Mật khẩu phải tối thiểu tám ký tự, ít nhất một chữ cái và một số")]

        public string MatKhau { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Mật khẩu không được trống")]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage ="Xác nhận mật không trùng khớp")]


        public string XacNhanMatKhau { get; set; }
    }
}
